### ISSUE TITLE
Missing $string['removemessages'] = 'Remove all journal entries'; from the en lang file

### ISSUE THREAD

**Issue by drachels** [dmonllao/moodle-mod_journal#17]
I was just doing some course resets and discovered there is a language string missing for doing that.
This is what needs to be added as about line 54 in the moodle/mod/journal/lang/en/journal.php file:
$string['removemessages'] = 'Remove all journal entries';

I've attached before and after pictures:

![removemessages1](https://cloud.githubusercontent.com/assets/1018249/12076384/a652ea96-b16f-11e5-9448-2deae10161b8.png)
![removemessages2](https://cloud.githubusercontent.com/assets/1018249/12076385/a960d1e4-b16f-11e5-88c5-0bd9bb0f55a1.png)

**Comment by dmonllao** [comment]
Thanks AL. Fix pushed to master, 30 and 29.
